name: main
run-name: main
on:
  push:
    branches:
      - master
    tags:
      - v0*
permissions:
  contents: write
jobs:
  test:
    uses: tbreslein/syke/.github/workflows/test.yml@master
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: get zig
        uses: mlugg/setup-zig@v1
      - name: build binaries
        run: |
          zig build --release=small -Dtarget=x86_64-linux -p .
          tar czf syke-x86_64-linux.tar.gz ./bin/syke ./LICENSE ./README.md

          zig build --release=small -Dtarget=aarch64-linux -p aarch64-linux
          tar czf syke-aarch64-linux.tar.gz ./bin/syke ./LICENSE ./README.md

          zig build --release=small -Dtarget=aarch64-macos -p aarch64-macos
          tar czf syke-aarch64-macos.tar.gz ./bin/syke ./LICENSE ./README.md
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            syke-x86_64-linux.tar.gz
            syke-aarch64-linux.tar.gz
            syke-aarch64-macos.tar.gz
            LICENSE
            README.md
